# Generated by Django 4.1.5 on 2023-01-31 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_productimage_delete_post_alter_product_prdcost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATName', models.CharField(max_length=50)),
                ('CATDesc', models.TextField()),
                ('CATImg', models.ImageField(upload_to='category/')),
                ('CATParent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.category')),
            ],
        ),
    ]
