# Generated by Django 4.1.5 on 2023-01-31 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_product_alternative_alter_category_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_Alternative',
        ),
    ]
