# Generated by Django 4.1.5 on 2023-01-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BRSName', models.CharField(max_length=40)),
                ('BRSDesc', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Veriant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VARSName', models.CharField(max_length=40)),
                ('VARSDesc', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Veriant',
                'verbose_name_plural': 'Veriants',
            },
        ),
    ]
